/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Assignment service. Represents a row in the &quot;CANVAS_Assignment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.AssignmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.AssignmentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Assignment
 * @see com.instructure.canvas.model.impl.AssignmentImpl
 * @see com.instructure.canvas.model.impl.AssignmentModelImpl
 * @generated
 */
public interface AssignmentModel extends BaseModel<Assignment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assignment model instance should use the {@link Assignment} interface instead.
	 */

	/**
	 * Returns the primary key of this assignment.
	 *
	 * @return the primary key of this assignment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assignment.
	 *
	 * @param primaryKey the primary key of this assignment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the assignment ID of this assignment.
	 *
	 * @return the assignment ID of this assignment
	 */
	public long getAssignmentId();

	/**
	 * Sets the assignment ID of this assignment.
	 *
	 * @param assignmentId the assignment ID of this assignment
	 */
	public void setAssignmentId(long assignmentId);

	/**
	 * Returns the name of this assignment.
	 *
	 * @return the name of this assignment
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this assignment.
	 *
	 * @param name the name of this assignment
	 */
	public void setName(String name);

	/**
	 * Returns the submission type of this assignment.
	 *
	 * @return the submission type of this assignment
	 */
	@AutoEscape
	public String getSubmissionType();

	/**
	 * Sets the submission type of this assignment.
	 *
	 * @param submissionType the submission type of this assignment
	 */
	public void setSubmissionType(String submissionType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Assignment assignment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Assignment> toCacheModel();

	@Override
	public Assignment toEscapedModel();

	@Override
	public Assignment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}