/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Award service. Represents a row in the &quot;CANVAS_Award&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.AwardModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.AwardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Award
 * @see com.instructure.canvas.model.impl.AwardImpl
 * @see com.instructure.canvas.model.impl.AwardModelImpl
 * @generated
 */
public interface AwardModel extends BaseModel<Award> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a award model instance should use the {@link Award} interface instead.
	 */

	/**
	 * Returns the primary key of this award.
	 *
	 * @return the primary key of this award
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this award.
	 *
	 * @param primaryKey the primary key of this award
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the award ID of this award.
	 *
	 * @return the award ID of this award
	 */
	public long getAwardId();

	/**
	 * Sets the award ID of this award.
	 *
	 * @param awardId the award ID of this award
	 */
	public void setAwardId(long awardId);

	/**
	 * Returns the cvl ID of this award.
	 *
	 * @return the cvl ID of this award
	 */
	@AutoEscape
	public String getCvlId();

	/**
	 * Sets the cvl ID of this award.
	 *
	 * @param cvlId the cvl ID of this award
	 */
	public void setCvlId(String cvlId);

	/**
	 * Returns the cvl name of this award.
	 *
	 * @return the cvl name of this award
	 */
	@AutoEscape
	public String getCvlName();

	/**
	 * Sets the cvl name of this award.
	 *
	 * @param cvlName the cvl name of this award
	 */
	public void setCvlName(String cvlName);

	/**
	 * Returns the score of this award.
	 *
	 * @return the score of this award
	 */
	public double getScore();

	/**
	 * Sets the score of this award.
	 *
	 * @param score the score of this award
	 */
	public void setScore(double score);

	/**
	 * Returns the letter article ID of this award.
	 *
	 * @return the letter article ID of this award
	 */
	public long getLetterArticleId();

	/**
	 * Sets the letter article ID of this award.
	 *
	 * @param letterArticleId the letter article ID of this award
	 */
	public void setLetterArticleId(long letterArticleId);

	/**
	 * Returns the certificate article ID of this award.
	 *
	 * @return the certificate article ID of this award
	 */
	public long getCertificateArticleId();

	/**
	 * Sets the certificate article ID of this award.
	 *
	 * @param certificateArticleId the certificate article ID of this award
	 */
	public void setCertificateArticleId(long certificateArticleId);

	/**
	 * Returns the active of this award.
	 *
	 * @return the active of this award
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this award is active.
	 *
	 * @return <code>true</code> if this award is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this award is active.
	 *
	 * @param active the active of this award
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this award.
	 *
	 * @return the create date of this award
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this award.
	 *
	 * @param createDate the create date of this award
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this award.
	 *
	 * @return the modified date of this award
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this award.
	 *
	 * @param modifiedDate the modified date of this award
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Award award);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Award> toCacheModel();

	@Override
	public Award toEscapedModel();

	@Override
	public Award toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}