/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CertLetterQueue service. Represents a row in the &quot;CANVAS_CertLetterQueue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.CertLetterQueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.CertLetterQueueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CertLetterQueue
 * @see com.instructure.canvas.model.impl.CertLetterQueueImpl
 * @see com.instructure.canvas.model.impl.CertLetterQueueModelImpl
 * @generated
 */
public interface CertLetterQueueModel extends BaseModel<CertLetterQueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cert letter queue model instance should use the {@link CertLetterQueue} interface instead.
	 */

	/**
	 * Returns the primary key of this cert letter queue.
	 *
	 * @return the primary key of this cert letter queue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cert letter queue.
	 *
	 * @param primaryKey the primary key of this cert letter queue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this cert letter queue.
	 *
	 * @return the ID of this cert letter queue
	 */
	public long getId();

	/**
	 * Sets the ID of this cert letter queue.
	 *
	 * @param id the ID of this cert letter queue
	 */
	public void setId(long id);

	/**
	 * Returns the course ID of this cert letter queue.
	 *
	 * @return the course ID of this cert letter queue
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this cert letter queue.
	 *
	 * @param courseId the course ID of this cert letter queue
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the create date of this cert letter queue.
	 *
	 * @return the create date of this cert letter queue
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cert letter queue.
	 *
	 * @param createDate the create date of this cert letter queue
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this cert letter queue.
	 *
	 * @return the created by of this cert letter queue
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this cert letter queue.
	 *
	 * @param createdBy the created by of this cert letter queue
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the status of this cert letter queue.
	 *
	 * @return the status of this cert letter queue
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this cert letter queue.
	 *
	 * @param status the status of this cert letter queue
	 */
	public void setStatus(String status);

	/**
	 * Returns the error description of this cert letter queue.
	 *
	 * @return the error description of this cert letter queue
	 */
	@AutoEscape
	public String getErrorDescription();

	/**
	 * Sets the error description of this cert letter queue.
	 *
	 * @param errorDescription the error description of this cert letter queue
	 */
	public void setErrorDescription(String errorDescription);

	/**
	 * Returns the error count of this cert letter queue.
	 *
	 * @return the error count of this cert letter queue
	 */
	public int getErrorCount();

	/**
	 * Sets the error count of this cert letter queue.
	 *
	 * @param errorCount the error count of this cert letter queue
	 */
	public void setErrorCount(int errorCount);

	/**
	 * Returns the modified date of this cert letter queue.
	 *
	 * @return the modified date of this cert letter queue
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cert letter queue.
	 *
	 * @param modifiedDate the modified date of this cert letter queue
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the start time of this cert letter queue.
	 *
	 * @return the start time of this cert letter queue
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this cert letter queue.
	 *
	 * @param startTime the start time of this cert letter queue
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this cert letter queue.
	 *
	 * @return the end time of this cert letter queue
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this cert letter queue.
	 *
	 * @param endTime the end time of this cert letter queue
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the zip file location of this cert letter queue.
	 *
	 * @return the zip file location of this cert letter queue
	 */
	@AutoEscape
	public String getZipFileLocation();

	/**
	 * Sets the zip file location of this cert letter queue.
	 *
	 * @param zipFileLocation the zip file location of this cert letter queue
	 */
	public void setZipFileLocation(String zipFileLocation);

	/**
	 * Returns the expiry date of this cert letter queue.
	 *
	 * @return the expiry date of this cert letter queue
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this cert letter queue.
	 *
	 * @param expiryDate the expiry date of this cert letter queue
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the type of this cert letter queue.
	 *
	 * @return the type of this cert letter queue
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this cert letter queue.
	 *
	 * @param type the type of this cert letter queue
	 */
	public void setType(String type);

	/**
	 * Returns the download date of this cert letter queue.
	 *
	 * @return the download date of this cert letter queue
	 */
	public Date getDownloadDate();

	/**
	 * Sets the download date of this cert letter queue.
	 *
	 * @param downloadDate the download date of this cert letter queue
	 */
	public void setDownloadDate(Date downloadDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CertLetterQueue certLetterQueue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CertLetterQueue> toCacheModel();

	@Override
	public CertLetterQueue toEscapedModel();

	@Override
	public CertLetterQueue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}