/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Course service. Represents a row in the &quot;CANVAS_Course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.CourseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.CourseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Course
 * @see com.instructure.canvas.model.impl.CourseImpl
 * @see com.instructure.canvas.model.impl.CourseModelImpl
 * @generated
 */
public interface CourseModel extends BaseModel<Course> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the canvas ID of this course.
	 *
	 * @return the canvas ID of this course
	 */
	public long getCanvasId();

	/**
	 * Sets the canvas ID of this course.
	 *
	 * @param canvasId the canvas ID of this course
	 */
	public void setCanvasId(long canvasId);

	/**
	 * Returns the name of this course.
	 *
	 * @return the name of this course
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this course.
	 *
	 * @param name the name of this course
	 */
	public void setName(String name);

	/**
	 * Returns the ID of this course.
	 *
	 * @return the ID of this course
	 */
	public long getId();

	/**
	 * Sets the ID of this course.
	 *
	 * @param id the ID of this course
	 */
	public void setId(long id);

	/**
	 * Returns the enrollments of this course.
	 *
	 * @return the enrollments of this course
	 */
	@AutoEscape
	public String getEnrollments();

	/**
	 * Sets the enrollments of this course.
	 *
	 * @param enrollments the enrollments of this course
	 */
	public void setEnrollments(String enrollments);

	/**
	 * Returns the course_code of this course.
	 *
	 * @return the course_code of this course
	 */
	@AutoEscape
	public String getCourse_code();

	/**
	 * Sets the course_code of this course.
	 *
	 * @param course_code the course_code of this course
	 */
	public void setCourse_code(String course_code);

	/**
	 * Returns the sis_course_id of this course.
	 *
	 * @return the sis_course_id of this course
	 */
	@AutoEscape
	public String getSis_course_id();

	/**
	 * Sets the sis_course_id of this course.
	 *
	 * @param sis_course_id the sis_course_id of this course
	 */
	public void setSis_course_id(String sis_course_id);

	/**
	 * Returns the calendar of this course.
	 *
	 * @return the calendar of this course
	 */
	@AutoEscape
	public String getCalendar();

	/**
	 * Sets the calendar of this course.
	 *
	 * @param calendar the calendar of this course
	 */
	public void setCalendar(String calendar);

	/**
	 * Returns the url of this course.
	 *
	 * @return the url of this course
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this course.
	 *
	 * @param url the url of this course
	 */
	public void setUrl(String url);

	/**
	 * Returns the netacad core offering ID of this course.
	 *
	 * @return the netacad core offering ID of this course
	 */
	@AutoEscape
	public String getNetacadCoreOfferingId();

	/**
	 * Sets the netacad core offering ID of this course.
	 *
	 * @param netacadCoreOfferingId the netacad core offering ID of this course
	 */
	public void setNetacadCoreOfferingId(String netacadCoreOfferingId);

	/**
	 * Returns the account ID of this course.
	 *
	 * @return the account ID of this course
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this course.
	 *
	 * @param accountId the account ID of this course
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the netacad c v l ID of this course.
	 *
	 * @return the netacad c v l ID of this course
	 */
	@AutoEscape
	public String getNetacadCVLId();

	/**
	 * Sets the netacad c v l ID of this course.
	 *
	 * @param netacadCVLId the netacad c v l ID of this course
	 */
	public void setNetacadCVLId(String netacadCVLId);

	/**
	 * Returns the start date of this course.
	 *
	 * @return the start date of this course
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this course.
	 *
	 * @param startDate the start date of this course
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this course.
	 *
	 * @return the end date of this course
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this course.
	 *
	 * @param endDate the end date of this course
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Course course);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Course> toCacheModel();

	@Override
	public Course toEscapedModel();

	@Override
	public Course toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}