/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EnrollmentSeat service. Represents a row in the &quot;CANVAS_EnrollmentSeat&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.EnrollmentSeatModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.EnrollmentSeatImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EnrollmentSeat
 * @see com.instructure.canvas.model.impl.EnrollmentSeatImpl
 * @see com.instructure.canvas.model.impl.EnrollmentSeatModelImpl
 * @generated
 */
public interface EnrollmentSeatModel extends BaseModel<EnrollmentSeat> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a enrollment seat model instance should use the {@link EnrollmentSeat} interface instead.
	 */

	/**
	 * Returns the primary key of this enrollment seat.
	 *
	 * @return the primary key of this enrollment seat
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this enrollment seat.
	 *
	 * @param primaryKey the primary key of this enrollment seat
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this enrollment seat.
	 *
	 * @return the ID of this enrollment seat
	 */
	public long getId();

	/**
	 * Sets the ID of this enrollment seat.
	 *
	 * @param id the ID of this enrollment seat
	 */
	public void setId(long id);

	/**
	 * Returns the token of this enrollment seat.
	 *
	 * @return the token of this enrollment seat
	 */
	@AutoEscape
	public String getToken();

	/**
	 * Sets the token of this enrollment seat.
	 *
	 * @param token the token of this enrollment seat
	 */
	public void setToken(String token);

	/**
	 * Returns the root account ID of this enrollment seat.
	 *
	 * @return the root account ID of this enrollment seat
	 */
	@AutoEscape
	public String getRootAccountId();

	/**
	 * Sets the root account ID of this enrollment seat.
	 *
	 * @param rootAccountId the root account ID of this enrollment seat
	 */
	public void setRootAccountId(String rootAccountId);

	/**
	 * Returns the course ID of this enrollment seat.
	 *
	 * @return the course ID of this enrollment seat
	 */
	@AutoEscape
	public String getCourseId();

	/**
	 * Sets the course ID of this enrollment seat.
	 *
	 * @param courseId the course ID of this enrollment seat
	 */
	public void setCourseId(String courseId);

	/**
	 * Returns the user ID of this enrollment seat.
	 *
	 * @return the user ID of this enrollment seat
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this enrollment seat.
	 *
	 * @param userId the user ID of this enrollment seat
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this enrollment seat.
	 *
	 * @return the user uuid of this enrollment seat
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this enrollment seat.
	 *
	 * @param userUuid the user uuid of this enrollment seat
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this enrollment seat.
	 *
	 * @return the create date of this enrollment seat
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this enrollment seat.
	 *
	 * @param createDate the create date of this enrollment seat
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the redeem date of this enrollment seat.
	 *
	 * @return the redeem date of this enrollment seat
	 */
	public Date getRedeemDate();

	/**
	 * Sets the redeem date of this enrollment seat.
	 *
	 * @param redeemDate the redeem date of this enrollment seat
	 */
	public void setRedeemDate(Date redeemDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EnrollmentSeat enrollmentSeat);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EnrollmentSeat> toCacheModel();

	@Override
	public EnrollmentSeat toEscapedModel();

	@Override
	public EnrollmentSeat toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}