/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Submission service. Represents a row in the &quot;CANVAS_Submission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.SubmissionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.SubmissionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Submission
 * @see com.instructure.canvas.model.impl.SubmissionImpl
 * @see com.instructure.canvas.model.impl.SubmissionModelImpl
 * @generated
 */
public interface SubmissionModel extends BaseModel<Submission> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a submission model instance should use the {@link Submission} interface instead.
	 */

	/**
	 * Returns the primary key of this submission.
	 *
	 * @return the primary key of this submission
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this submission.
	 *
	 * @param primaryKey the primary key of this submission
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the submission ID of this submission.
	 *
	 * @return the submission ID of this submission
	 */
	public long getSubmissionId();

	/**
	 * Sets the submission ID of this submission.
	 *
	 * @param submissionId the submission ID of this submission
	 */
	public void setSubmissionId(long submissionId);

	/**
	 * Returns the assignment ID of this submission.
	 *
	 * @return the assignment ID of this submission
	 */
	public long getAssignmentId();

	/**
	 * Sets the assignment ID of this submission.
	 *
	 * @param assignmentId the assignment ID of this submission
	 */
	public void setAssignmentId(long assignmentId);

	/**
	 * Returns the course ID of this submission.
	 *
	 * @return the course ID of this submission
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this submission.
	 *
	 * @param courseId the course ID of this submission
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the attempt of this submission.
	 *
	 * @return the attempt of this submission
	 */
	public int getAttempt();

	/**
	 * Sets the attempt of this submission.
	 *
	 * @param attempt the attempt of this submission
	 */
	public void setAttempt(int attempt);

	/**
	 * Returns the grade of this submission.
	 *
	 * @return the grade of this submission
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this submission.
	 *
	 * @param grade the grade of this submission
	 */
	public void setGrade(String grade);

	/**
	 * Returns the html url of this submission.
	 *
	 * @return the html url of this submission
	 */
	@AutoEscape
	public String getHtmlUrl();

	/**
	 * Sets the html url of this submission.
	 *
	 * @param htmlUrl the html url of this submission
	 */
	public void setHtmlUrl(String htmlUrl);

	/**
	 * Returns the score of this submission.
	 *
	 * @return the score of this submission
	 */
	public double getScore();

	/**
	 * Sets the score of this submission.
	 *
	 * @param score the score of this submission
	 */
	public void setScore(double score);

	/**
	 * Returns the submission date of this submission.
	 *
	 * @return the submission date of this submission
	 */
	@AutoEscape
	public String getSubmissionDate();

	/**
	 * Sets the submission date of this submission.
	 *
	 * @param submissionDate the submission date of this submission
	 */
	public void setSubmissionDate(String submissionDate);

	/**
	 * Returns the grader ID of this submission.
	 *
	 * @return the grader ID of this submission
	 */
	@AutoEscape
	public String getGraderId();

	/**
	 * Sets the grader ID of this submission.
	 *
	 * @param graderId the grader ID of this submission
	 */
	public void setGraderId(String graderId);

	/**
	 * Returns the user ID of this submission.
	 *
	 * @return the user ID of this submission
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this submission.
	 *
	 * @param userId the user ID of this submission
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this submission.
	 *
	 * @return the user uuid of this submission
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this submission.
	 *
	 * @param userUuid the user uuid of this submission
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Submission submission);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Submission> toCacheModel();

	@Override
	public Submission toEscapedModel();

	@Override
	public Submission toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}