/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Todo service. Represents a row in the &quot;CANVAS_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.instructure.canvas.model.impl.TodoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.instructure.canvas.model.impl.TodoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Todo
 * @see com.instructure.canvas.model.impl.TodoImpl
 * @see com.instructure.canvas.model.impl.TodoModelImpl
 * @generated
 */
public interface TodoModel extends BaseModel<Todo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo model instance should use the {@link Todo} interface instead.
	 */

	/**
	 * Returns the primary key of this todo.
	 *
	 * @return the primary key of this todo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo.
	 *
	 * @param primaryKey the primary key of this todo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the todo ID of this todo.
	 *
	 * @return the todo ID of this todo
	 */
	public long getTodoId();

	/**
	 * Sets the todo ID of this todo.
	 *
	 * @param todoId the todo ID of this todo
	 */
	public void setTodoId(long todoId);

	/**
	 * Returns the type of this todo.
	 *
	 * @return the type of this todo
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this todo.
	 *
	 * @param type the type of this todo
	 */
	public void setType(String type);

	/**
	 * Returns the assignment name of this todo.
	 *
	 * @return the assignment name of this todo
	 */
	@AutoEscape
	public String getAssignmentName();

	/**
	 * Sets the assignment name of this todo.
	 *
	 * @param assignmentName the assignment name of this todo
	 */
	public void setAssignmentName(String assignmentName);

	/**
	 * Returns the assignment description of this todo.
	 *
	 * @return the assignment description of this todo
	 */
	@AutoEscape
	public String getAssignmentDescription();

	/**
	 * Sets the assignment description of this todo.
	 *
	 * @param assignmentDescription the assignment description of this todo
	 */
	public void setAssignmentDescription(String assignmentDescription);

	/**
	 * Returns the ignore_ of this todo.
	 *
	 * @return the ignore_ of this todo
	 */
	@AutoEscape
	public String getIgnore_();

	/**
	 * Sets the ignore_ of this todo.
	 *
	 * @param ignore_ the ignore_ of this todo
	 */
	public void setIgnore_(String ignore_);

	/**
	 * Returns the ignore permanently of this todo.
	 *
	 * @return the ignore permanently of this todo
	 */
	@AutoEscape
	public String getIgnorePermanently();

	/**
	 * Sets the ignore permanently of this todo.
	 *
	 * @param ignorePermanently the ignore permanently of this todo
	 */
	public void setIgnorePermanently(String ignorePermanently);

	/**
	 * Returns the needs grading count of this todo.
	 *
	 * @return the needs grading count of this todo
	 */
	public long getNeedsGradingCount();

	/**
	 * Sets the needs grading count of this todo.
	 *
	 * @param needsGradingCount the needs grading count of this todo
	 */
	public void setNeedsGradingCount(long needsGradingCount);

	/**
	 * Returns the context type of this todo.
	 *
	 * @return the context type of this todo
	 */
	@AutoEscape
	public String getContextType();

	/**
	 * Sets the context type of this todo.
	 *
	 * @param contextType the context type of this todo
	 */
	public void setContextType(String contextType);

	/**
	 * Returns the course ID of this todo.
	 *
	 * @return the course ID of this todo
	 */
	@AutoEscape
	public String getCourseId();

	/**
	 * Sets the course ID of this todo.
	 *
	 * @param courseId the course ID of this todo
	 */
	public void setCourseId(String courseId);

	/**
	 * Returns the group ID of this todo.
	 *
	 * @return the group ID of this todo
	 */
	@AutoEscape
	public String getGroupId();

	/**
	 * Sets the group ID of this todo.
	 *
	 * @param groupId the group ID of this todo
	 */
	public void setGroupId(String groupId);

	/**
	 * Returns the html url of this todo.
	 *
	 * @return the html url of this todo
	 */
	@AutoEscape
	public String getHtmlUrl();

	/**
	 * Sets the html url of this todo.
	 *
	 * @param htmlUrl the html url of this todo
	 */
	public void setHtmlUrl(String htmlUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Todo todo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Todo> toCacheModel();

	@Override
	public Todo toEscapedModel();

	@Override
	public Todo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}