/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.instructure.canvas.model.impl;

import com.instructure.canvas.model.UserAward;
import com.instructure.canvas.service.UserAwardLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the UserAward service. Represents a row in the &quot;CANVAS_UserAward&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserAwardImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserAwardImpl
 * @see com.instructure.canvas.model.UserAward
 * @generated
 */
public abstract class UserAwardBaseImpl extends UserAwardModelImpl
	implements UserAward {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user award model instance should use the {@link UserAward} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			UserAwardLocalServiceUtil.addUserAward(this);
		}
		else {
			UserAwardLocalServiceUtil.updateUserAward(this);
		}
	}
}